version: "3.8"
services: 

    kibana:
        image: kibana:7.9.1
        container_name: kibana
        restart: always
        volumes: 
            - type: bind
              source: ./confFiles/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        depends_on: 
            - elastic
        ports:
            - "5601:5601"
        networks:
            - elk
        # environment: 
            # SERVER_HOST: 0.0.0.0
            # ELASTICSEARCH_URL: http://elastic:9200
        
    elastic:
        image: elasticsearch:7.9.1
        container_name: elastic
        restart: always
        volumes: 
            - type: bind
              source: ./confFiles/elasticsearch.yml
              target: /usr/share/elasticsearch/config/elasticsearch.yml
              read_only: true
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            # ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
            # ELASTIC_PASSWORD: changeme
            - "discovery.type=single-node"
        networks:
            - elk

    logstash:
        image: logstash:7.9.1
        container_name: logstash
        restart: always
        volumes: 
            - type: bind
              source: ./confFiles/logstash.yml
              target: /usr/share/logstash/config/logstash.yml
              read_only: true
            - type: bind
              source: ./confFiles/pipeline
              target: /usr/share/logstash/pipeline
              read_only: true
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment: 
            ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
        networks:
            - elk
        depends_on: 
            - kibana
            - elastic

networks:
    elk:
        driver: bridge
